name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '01 9 * * 1-5'
    - cron:  '01 15 * * 1-5'
    - cron:  '01 18 * * 1-5'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4


    - name: Get changed files 1
      id: changes
      uses: tj-actions/changed-files@v35
      with:
        files: 'data/**'
    - name: Debug changed files
      run: |
        echo "Any changed[1]: ${{ steps.changes.outputs.any_changed }}"
        echo "All changed files[1]: ${{ steps.changes.outputs.all_changed_files }}"
        echo "Added files[1]: ${{ steps.changes.outputs.added_files }}"
        echo "Modified files[1]: ${{ steps.changes.outputs.modified_files }}"
        echo "Removed files[1]: ${{ steps.changes.outputs.removed_files }}"


    - name: Push some files inside the workflow run
      run: |
        # Configure Git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Create a dummy file
        echo "This is a dummy file 3." > dummy3.txt

        # Add and commit the dummy file
        git add dummy.txt
        git commit -m "Add dummy file for testing"

        # Output the repository URL and branch for debugging
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"

        git push origin HEAD:${{ github.ref }}
      env:
        GH_PAT: ${{ secrets.GH_PAT }}



    - name: Get changed files 2
      id: changes2
      uses: tj-actions/changed-files@v35
      with:
        files: 'data/**'
    - name: Debug changed files 2
      run: |
        echo "Any changed[2]: ${{ steps.changes2.outputs.any_changed }}"
        echo "All changed files[2]: ${{ steps.changes2.outputs.all_changed_files }}"
        echo "Added files[2]: ${{ steps.changes2.outputs.added_files }}"
        echo "Modified files[2]: ${{ steps.changes2.outputs.modified_files }}"
        echo "Removed files[2]: ${{ steps.changes2.outputs.removed_files }}"

    - name: Trigger repository_dispatch in labanca/cc-dispatch-dados-link-obz-2025
      if: steps.changes.outputs.any_changed == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          https://api.github.com/repos/labanca/cc-dispatch-dados-link-obz-2025/dispatches \
          -d '{"event_type":"trigger-workflow"}'
