name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '01 9 * * 1-5'
    - cron:  '01 15 * * 1-5'
    - cron:  '01 18 * * 1-5'

jobs:
  all:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Get changed files 1
      id: changes
      uses: tj-actions/changed-files@v35
      with:
        files: 'data/**'
    - name: Debug changed files
      run: |
        echo "Any changed[1]: ${{ steps.changes.outputs.any_changed }}"
        echo "All changed files[1]: ${{ steps.changes.outputs.all_changed_files }}"
        echo "Added files[1]: ${{ steps.changes.outputs.added_files }}"
        echo "Modified files[1]: ${{ steps.changes.outputs.modified_files }}"
        echo "Removed files[1]: ${{ steps.changes.outputs.removed_files }}"
      push_depth: 0



    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: fjuniorr/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=fjuniorr/${{ github.event.repository.name }}:latest
        cache-to: type=inline
    - name: ETL pipeline
      run: docker run --rm --mount type=bind,source=${PWD},target=/project fjuniorr/${{ github.event.repository.name }} make all
    - name: ETL pipeline notification
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        docker run -e GITHUB_TOKEN=$GITHUB_TOKEN --rm --mount type=bind,source=${PWD},target=/project fjuniorr/${{ github.event.repository.name }} make notify
    - name: Publish data package
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        make publish

    - name: Get changed files 2
      id: changes
      uses: tj-actions/changed-files@v35
      with:
        files: 'data/**'
    - name: Debug changed files
      run: |
        echo "Any changed[2]: ${{ steps.changes.outputs.any_changed }}"
        echo "All changed files[2]: ${{ steps.changes.outputs.all_changed_files }}"
        echo "Added files[2]: ${{ steps.changes.outputs.added_files }}"
        echo "Modified files[2]: ${{ steps.changes.outputs.modified_files }}"
        echo "Removed files[2]: ${{ steps.changes.outputs.removed_files }}"
      push_depth: 0

    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUNID: ${{ github.run_id }}
      with:
        filename: .github/workflow-failure.md



    - name: Trigger repository_dispatch in labanca/cc-dispatch-dados-link-obz-2025
      if: steps.changes.outputs.any_changed == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          https://api.github.com/repos/labanca/cc-dispatch-dados-link-obz-2025/dispatches \
          -d '{"event_type":"trigger-workflow"}'
