name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '01 9 * * 1-5'
    - cron:  '01 15 * * 1-5'
    - cron:  '01 18 * * 1-5'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Get changed files
      id: changes
      uses: tj-actions/changed-files@v35
      with:
        files: 'data/**'

    - name: Trigger repository_dispatch in labanca/cc-dispatch-dados-link-obz-2025
      if: steps.changes.outputs.any_changed == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          https://api.github.com/repos/labanca/cc-dispatch-dados-link-obz-2025/dispatches \
          -d '{"event_type":"trigger-workflow"}'
