name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '13 8 * * 1-5'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    # Add steps to handle the dispatch event
    - name: Run script
      run: echo "Repository dispatch event triggered!"
