name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '13 8 * * 1-5'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v44
            - name: List all changed files
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              run: |
                for file in ${ALL_CHANGED_FILES}; do
                  echo "$file was changed"
                done
    - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
    - name: Trigger repository_dispatch in splor-mg/dados-link-obz-2025
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          https://api.github.com/repos/labanca/cc-dispatch-dados-link-obz-2025/dispatches \
          -d '{"event_type":"trigger-workflow"}'
